import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeToggle/theme-provider";
import Header from "@/components/Header";

import { Button } from "@/components/ui/button";
import { EthProvider } from "@/context/eathContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Etherscan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
          </ThemeProvider>
        </EthProvider>
      </body>
    </html>
  );
}
